# Generated by Django 2.1.1 on 2018-09-30 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('b', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Business')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Application'),
        ),
        migrations.AddField(
            model_name='app',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Host'),
        ),
    ]
